In [1]:
#assignment3
#Q1
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)

[ 6.5  8.5 10.5 12.5]
[-4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34. ]
[0.18181818 0.30769231 0.4        0.47058824]
[0. 0. 0. 0.]


In [3]:
#Q2
X = np.array([[1,2],[3,4]])
print(np.sqrt(X))
print(np.exp(X))
print(np.min(X,axis=0))
print(np.max(X,axis=0))
print(np.median(X,axis=0))
print(np.std(X,axis=0))
print(np.mean(X,axis=0))
print(np.min(X,axis=1))
print(np.max(X,axis=1))
print(np.median(X,axis=1))
print(np.std(X,axis=1))
print(np.mean(X,axis=1))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[1 2]
[3 4]
[2. 3.]
[1. 1.]
[2. 3.]
[1 3]
[2 4]
[1.5 3.5]
[0.5 0.5]
[1.5 3.5]
